"""Type definitions for the product refinement system."""
from typing import TypedDict, List

class Question(TypedDict):
    """Represents a question generated by the AI."""
    section: str
    question: str

class AnsweredQuestion(Question):
    """Represents a question that has been answered by the user."""
    answer: str

class SpecificationVersion(TypedDict):
    """Represents a version of a specification."""
    filename: str
    version: int
    timestamp: float
    formatted_timestamp: str
    product_name: str

class SpecificationData(TypedDict):
    """Represents the data structure of a specification JSON file."""
    version: int
    timestamp: float
    formatted_timestamp: str
    product_name: str
    specification: str
    doc_type: str  # Added document type

class DocumentDependency(TypedDict):
    """Defines a dependency between document types."""
    source_type: str      # The document type this depends on
    source_field: str     # The field needed from the source document
    placeholder: str      # The placeholder in the prompt to be replaced