"""Type definitions for the product refinement system."""
from typing import TypedDict

class Question(TypedDict):
    """Represents a question generated by the AI."""
    section: str
    question: str

class AnsweredQuestion(Question):
    """Represents a question that has been answered by the user."""
    answer: str

class SpecificationVersion(TypedDict):
    """Represents a version of a specification."""
    filename: str
    version: int
    timestamp: float
    formatted_timestamp: str
    product_name: str

class SpecificationData(TypedDict):
    """Represents the data structure of a specification JSON file."""
    version: int
    timestamp: float
    formatted_timestamp: str
    product_name: str
    specification: str 